codecov:
  # CI Pipeline fails if code-coverage does not meet standards
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...90"   # code coverage between 75-90% would be okay
  status:
    project:
      # Comparisions made against base of PR, or parent commit
      default:
        threshold: 20%  # Coverage can drop by at most 20% and still pass
        target: 70%     # Coverage below 70% is a fail

    patch:
      # Measures lines modified in an individual commit/PR
      default:
        threshold: 30%
        target: 70%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
